/**
 * FocusGuard WebRTC Mesh Network Handler
 * Handles direct peer-to-peer video streaming using standard WebRTC APIs
 * Coordinates handshakes through the Flask-SocketIO signalling backend
 */

class WebRTCHandler {
    constructor(meetingId, userId, username, localStream, onRemoteStreamAdded, onRemoteStreamRemoved) {
        this.meetingId = meetingId;
        this.userId = userId;
        this.username = username;
        this.localStream = localStream;
        this.onRemoteStreamAdded = onRemoteStreamAdded;
        this.onRemoteStreamRemoved = onRemoteStreamRemoved;

        this.peers = {}; // Map of userId -> RTCPeerConnection
        this.socket = null;

        // Free Google Public STUN Configuration
        this.rtcConfig = {
            iceServers: [
                { urls: 'stun:stun.l.google.com:19302' },
                { urls: 'stun:stun1.l.google.com:19302' }
            ]
        };
    }

    initialize() {
        // Connect to Socket.IO signaling server
        const socketUrl = window.location.origin;
        this.socket = io(socketUrl);

        this.socket.on('connect', () => {
            console.log('Signaling server connected. Joining room:', this.meetingId);
            this.socket.emit('join-room', {
                meeting_id: this.meetingId,
                user_id: this.userId,
                username: this.username
            });
        });

        // Event: A new peer joined. Initiate WebRTC handshake.
        this.socket.on('peer-joined', async (data) => {
            const peerId = data.user_id;
            const peerName = data.username;
            console.log('Peer joined room:', peerName, peerId);
            
            const peerConnection = this.createPeerConnection(peerId, peerName);
            
            // Create offer
            const offer = await peerConnection.createOffer();
            await peerConnection.setLocalDescription(offer);
            
            this.socket.emit('webrtc-offer', {
                meeting_id: this.meetingId,
                sender_id: this.userId,
                sender_username: this.username,
                sdp: offer
            });
        });

        // Event: Received WebRTC Offer from a peer. Set remote SDP and reply with Answer.
        this.socket.on('webrtc-offer', async (data) => {
            const peerId = data.sender_id;
            const peerName = data.sender_username;
            console.log('Received WebRTC offer from:', peerName);

            const peerConnection = this.createPeerConnection(peerId, peerName);
            await peerConnection.setRemoteDescription(new RTCSessionDescription(data.sdp));

            const answer = await peerConnection.createAnswer();
            await peerConnection.setLocalDescription(answer);

            this.socket.emit('webrtc-answer', {
                meeting_id: this.meetingId,
                sender_id: this.userId,
                sdp: answer
            });
        });

        // Event: Received WebRTC Answer. Set remote description.
        this.socket.on('webrtc-answer', async (data) => {
            const peerId = data.sender_id;
            console.log('Received WebRTC answer from peer:', peerId);
            const peerConnection = this.peers[peerId];
            if (peerConnection) {
                await peerConnection.setRemoteDescription(new RTCSessionDescription(data.sdp));
            }
        });

        // Event: Received ICE Candidate. Add to connection.
        this.socket.on('ice-candidate', async (data) => {
            const peerId = data.sender_id;
            const peerConnection = this.peers[peerId];
            if (peerConnection && data.candidate) {
                try {
                    await peerConnection.addIceCandidate(new RTCIceCandidate(data.candidate));
                } catch (e) {
                    console.error('Error adding received ice candidate:', e);
                }
            }
        });

        // Event: Peer disconnected
        this.socket.on('peer-left', (data) => {
            const peerId = data.user_id;
            console.log('Peer left meeting room:', peerId);
            this.closePeerConnection(peerId);
        });
    }

    createPeerConnection(peerId, peerName) {
        if (this.peers[peerId]) {
            this.closePeerConnection(peerId);
        }

        const pc = new RTCPeerConnection(this.rtcConfig);

        // Add local camera & mic tracks to the connection
        if (this.localStream) {
            this.localStream.getTracks().forEach(track => {
                pc.addTrack(track, this.localStream);
            });
        }

        // Handle candidates generated by browser locally
        pc.onicecandidate = (event) => {
            if (event.candidate) {
                this.socket.emit('ice-candidate', {
                    meeting_id: this.meetingId,
                    sender_id: this.userId,
                    candidate: event.candidate
                });
            }
        };

        // Handle remote stream tracks arriving from this peer
        pc.ontrack = (event) => {
            console.log('Received remote track from peer:', peerName);
            if (this.onRemoteStreamAdded) {
                this.onRemoteStreamAdded(peerId, peerName, event.streams[0]);
            }
        };

        pc.onconnectionstatechange = () => {
            console.log(`Connection state change with ${peerName}: ${pc.connectionState}`);
            if (pc.connectionState === 'disconnected' || pc.connectionState === 'failed') {
                this.closePeerConnection(peerId);
            }
        };

        this.peers[peerId] = pc;
        return pc;
    }

    closePeerConnection(peerId) {
        const pc = this.peers[peerId];
        if (pc) {
            pc.close();
            delete this.peers[peerId];
        }
        if (this.onRemoteStreamRemoved) {
            this.onRemoteStreamRemoved(peerId);
        }
    }

    leave() {
        if (this.socket) {
            this.socket.emit('leave-room', {
                meeting_id: this.meetingId,
                user_id: this.userId
            });
            this.socket.disconnect();
        }

        // Close all peer connections
        Object.keys(this.peers).forEach(peerId => {
            this.closePeerConnection(peerId);
        });
    }
}
